#pragma once

const unsigned int WINCX = 800;
const unsigned int WINCY = 600;

const int iCubeIndex = 17;
const int iObjIndex = 16;
const int iMonIndex = 8;
const int iItemIndex = 11;

enum SCENETYPE { SCENE_STATIC, SCENE_LOGO, SCENE_MENU, SCENE_STAGE1, SCENE_STAGE2, SCENE_STAGE3, SCENE_END };
enum ITEMTYPE  { ITEM_HP_LOW, ITEM_HP_MEDIUM, ITEM_HP_HIGH, ITEM_BULLET,
			     ITEM_GUARD_SMALL, ITEM_GUARD_MEDIUM, ITEM_GUARD_HIGH,
				 ITEM_GUN_BMG, ITEM_GUN_SHOTGUN, ITEM_GUN_CHAINGUN, ITEM_GUN_PLASMA};

enum MONSTERTYPE { MONSTER_IMP, MONSTER_DEMON, MONSTER_DECO, MONSTER_AFRIT, MONSTER_BARON, MONSTER_SEGERENT, MONSTER_ELEMENT, MONSTER_NORM_SOLDIER };